[project]
name = "Kateto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "torch",
  "torchaudio>=2.11.0",
  "triton-rocm",
  "pytorch-triton-rocm>=3.5.1; sys_platform == 'linux'",
  "aule-attention>=0.5.0",
  "xformers>=0.0.35",
  "bitsandbytes>=0.49.2",
  "accelerate>=1.12.0",
]

[tool.uv.workspace]
members = [
  "apps/classifier",
  "apps/orchestator",
  "apps/tts",
  "packages/protos",
  "packages/protos/*",
  "apps/lang_manager",
  "apps/manager",
  "packages/data",
  "packages/i_have_time",
  "packages/op-client",
]
exclude = ["**/node_modules", "**/__pycache__"]

[tool.uv]
index-strategy = "unsafe-best-match"
no-build-isolation-package = ["flash-attn", "setuptools"]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"

[[tool.uv.index]]
name = "xformers"
url = "https://download.pytorch.org/whl/rocm7.1"

[tool.uv.sources]
torch = { index = "pytorch-rocm" }
torchaudio = { index = "pytorch-rocm" }
pytorch-triton-rocm = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
triton-rocm = { index = "pytorch-rocm" }

[tool.pyright]
venvPath = "./"
venv = ".venv"
