# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classifier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lassifier.proto\"\x1d\n\x0b\x42\x65rtRequest\x12\x0e\n\x06prompt\x18\x01 \x02(\t\"&\n\x0c\x42\x65rtResponse\x12\x16\n\x05label\x18\x01 \x02(\x0e\x32\x07.Labels*\x1d\n\x06Labels\x12\x08\n\x04talk\x10\x00\x12\t\n\x05think\x10\x01\x32\x35\n\nClassifier\x12\'\n\x08\x43lassify\x12\x0c.BertRequest\x1a\r.BertResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LABELS']._serialized_start=91
  _globals['_LABELS']._serialized_end=120
  _globals['_BERTREQUEST']._serialized_start=20
  _globals['_BERTREQUEST']._serialized_end=49
  _globals['_BERTRESPONSE']._serialized_start=51
  _globals['_BERTRESPONSE']._serialized_end=89
  _globals['_CLASSIFIER']._serialized_start=122
  _globals['_CLASSIFIER']._serialized_end=175
# @@protoc_insertion_point(module_scope)
